[%
  # T: Chaînes de caractères utilisées dans l'interface de configuration du plugin.
  T = {
    #
    # === text générale ===
    #
    title = "Celebrations Plugin",
    titreD = "Welcome to the Celebration plugin!",
    description1 = "This plugin allows you to add seasonal themes to Koha's OPAC, such as Christmas, Halloween, or Valentine's Day.",
    description2 = "You can also customize some visual effects for each active theme.",
    select_theme = "Select an OPAC Theme",
    apply_button = "Apply Theme",
    apply_success = "✅ Theme applied successfully!",
    apply_error = "❌ An error occurred while applying the theme. :(",
    #
    # === Nom des themes disponible ===
    #
    form = {
      theme_label = "Theme:",
      no_theme = "None",
      noel = "Christmas",
      halloween = "Halloween",
      "saint-valentin" = "Valentine's Day",
      paque = "Easter",
      "feux-artifice" = "Fireworks"
    },
    #
    # === configuration du theme noel ===
    #
    noel = {
        couleur_noel = "Enable Christmas Color 🔴 🟢 ⚪",
        footer_noel = "Enable Footer elements ✨",
        activation_flocons = "Enable snow effect ❄️",
        vitesse_flocons = "Snow speed:",
        taille_flocons = "Flake size:",
        vent_flocons = "Wind:",
        quantite_flocons = "Quantity:",
    },
    #
    # === configuration du theme saint-valentin ===
    #
    "saint-valentin" = {
        couleur_valentin = "Enable Valentine Color ⚪ 🩷 ⚪",
        activation_coeurs = "Enable heart effect ❤️",
        vitesse_coeurs = "Heart speed:",
        taille_coeurs = "Heart size:",
        vent_coeurs = "Wind:",
        quantite_coeurs = "Quantity:",
    },
    #
    # === configuration du theme halloween ===
    #
    halloween = {
        couleur_halloween = "Enable Halloween Color 🟠 ⚫",
        footer_halloween = "Enable Footer elements 🎃",
        activation_spiders = "Enable spider effect 🕷️",
        quantite_spiders = "Number of spiders:",
        activation_ghost = "Enable ghost cursor 👻",
    },
    #
    # === configuration du theme paque ===
    #
    paque = {
        couleur_paque = "Enable Easter Color 🟡 🟢 🟣",
        footer_paque = "Enable Footer elements 🧺🥚",
        activation_eggs = "Enable eggs cursor 🥚",
    },
    #
    # === configuration du theme feux-artifice ===
    #
    "feux-artifice" = {
        couleur_feux = "Enable fire work Color 🟣 ⚫ 🟢",
        animation_feux = "Enable fire work animation 🎆",
    },
    #
    # === configuration des option de vitesse ===
    #
    option_vitesse = {
        vitesse_lent = "Slow",
        vitesse_normale = "Normal",
        vitesse_rapide = "Fast",
    }
    #
    # === configuration des option de taille ===
    #
    option_taille = {
        taille_petit = "Small",
        taille_normale = "Normal",
        taille_grand = "Big",
    }
    #
    # === configuration des option de vent ===
    #
    option_vent = {
        vent_null = "None",
        vent_normale = "Normal",
        vent_fort = "A lot",
    }
  },
   # D: Chaînes de caractères affichées lorsque le plugin est DÉSACTIVÉ.
   D = {
    titre = "Welcome to the Celebration plugin!",
    description1 = "Holidays and celebrations are here to remind us to",
    description2 = "take time to smile",
    description3 = ", share joyful moments, and add a splash of color to our days ✨.",
    description4 = "But wait!",
    description5 = "This plugin is currently",
    description6 = "disabled.",
    description7 = "To access its configuration and enjoy all its features, please return to the plugins page and",
    description8 = "enable Celebration.",
    btn_back = "← Back to plugins page"
  }
%]